package Vista;

import java.sql.Statement;
import java.sql.Connection;
import cxbasedatos.Conexion;
import java.awt.Color;
import java.awt.FlowLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;



public class registro extends javax.swing.JFrame {
    Conexion con1 = new Conexion();
    Connection conet;
    DefaultTableModel modelo;
    Statement st;
    ResultSet rs;
    int idc;
    public registro() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        consultar();
        estadisticas();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PanelEstadisticas = new javax.swing.JPanel();
        foto1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PanelActividades = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        foto3 = new javax.swing.JLabel();
        PanelRegistrar = new javax.swing.JPanel();
        foto2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        labelMin = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        estudiantesPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtApe = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        estadisticasPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanelEstadisticas = new javax.swing.JPanel();
        acercaPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estudiar.png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 260, 180));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondomoradosuperior.png"))); // NOI18N
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 300));

        PanelEstadisticas.setBackground(new java.awt.Color(102, 102, 255));
        PanelEstadisticas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelEstadisticas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PanelEstadisticasMouseMoved(evt);
            }
        });
        PanelEstadisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelEstadisticasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelEstadisticasMouseExited(evt);
            }
        });
        PanelEstadisticas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/analitica (1).png"))); // NOI18N
        PanelEstadisticas.add(foto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 60, 60));

        jLabel9.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        jLabel9.setText("ESTADISTICAS");
        PanelEstadisticas.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jPanel4.add(PanelEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 310, 60));

        PanelActividades.setBackground(new java.awt.Color(102, 102, 255));
        PanelActividades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelActividades.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PanelActividadesMouseMoved(evt);
            }
        });
        PanelActividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelActividadesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelActividadesMouseExited(evt);
            }
        });
        PanelActividades.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        jLabel10.setText("ACERCA DE");
        PanelActividades.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        foto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grupo (1).png"))); // NOI18N
        PanelActividades.add(foto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 60, 60));

        jPanel4.add(PanelActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 310, 60));

        PanelRegistrar.setBackground(new java.awt.Color(102, 102, 255));
        PanelRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelRegistrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PanelRegistrarMouseMoved(evt);
            }
        });
        PanelRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelRegistrarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelRegistrarMouseExited(evt);
            }
        });
        PanelRegistrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        foto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir.png"))); // NOI18N
        PanelRegistrar.add(foto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 60, 60));

        jLabel11.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        jLabel11.setText("REGISTRAR ");
        PanelRegistrar.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jPanel4.add(PanelRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 310, 60));

        jLabel13.setFont(new java.awt.Font("Courier 10 Pitch", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Sistema SGRE");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 310, 850));

        labelMin.setFont(new java.awt.Font("Liberation Sans", 0, 50)); // NOI18N
        labelMin.setText("-");
        labelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMinMouseClicked(evt);
            }
        });
        getContentPane().add(labelMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 10, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoProyecto.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 100, 60));

        jLabel7.setFont(new java.awt.Font("Courier 10 Pitch", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sistema SGRE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jLabel15.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        jLabel15.setText("x");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1450, 10, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondomoradosuperior.png"))); // NOI18N
        jLabel17.setText("zx");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 1200, 80));

        jTabbedPane.setBackground(new java.awt.Color(255, 255, 255));

        estudiantesPanel.setBackground(new java.awt.Color(204, 204, 255));
        estudiantesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier 10 Pitch", 0, 36)); // NOI18N
        jLabel1.setText("REGISTRO ESTUDIANTES");
        estudiantesPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel2.setText("ID:");

        txtId.setEditable(false);
        txtId.setEnabled(false);

        jLabel3.setText("NOMBRE:");

        jLabel4.setText("APELLIDOS:");

        jLabel5.setText("EDAD:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(txtNombre)
                    .addComponent(txtApe)
                    .addComponent(txtEdad))
                .addContainerGap(500, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        estudiantesPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 760, 220));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Operaciones"));

        btnModificar.setText("MODIFICAR");
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnAgregar.setText("AGREGAR");
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnNuevo.setText("NUEVO");
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        estudiantesPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 760, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Base de Datos"));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nombre", "apellido", "edad"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabla);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        estudiantesPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 760, -1));

        jTabbedPane.addTab("tab1", estudiantesPanel);

        jLabel12.setFont(new java.awt.Font("Courier 10 Pitch", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 51, 255));
        jLabel12.setText("ESTADISTICAS DE ESTUDIANTES");

        javax.swing.GroupLayout jPanelEstadisticasLayout = new javax.swing.GroupLayout(jPanelEstadisticas);
        jPanelEstadisticas.setLayout(jPanelEstadisticasLayout);
        jPanelEstadisticasLayout.setHorizontalGroup(
            jPanelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        jPanelEstadisticasLayout.setVerticalGroup(
            jPanelEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout estadisticasPanelLayout = new javax.swing.GroupLayout(estadisticasPanel);
        estadisticasPanel.setLayout(estadisticasPanelLayout);
        estadisticasPanelLayout.setHorizontalGroup(
            estadisticasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(estadisticasPanelLayout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel12)
                .addContainerGap(374, Short.MAX_VALUE))
            .addGroup(estadisticasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(estadisticasPanelLayout.createSequentialGroup()
                    .addGap(0, 60, Short.MAX_VALUE)
                    .addComponent(jPanelEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 60, Short.MAX_VALUE)))
        );
        estadisticasPanelLayout.setVerticalGroup(
            estadisticasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(estadisticasPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel12)
                .addContainerGap(677, Short.MAX_VALUE))
            .addGroup(estadisticasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(estadisticasPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanelEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane.addTab("tab2", estadisticasPanel);

        acercaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(86, 31, 223), 5));
        jPanel8.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Dosquebradas");
        jPanel8.add(jLabel19);
        jLabel19.setBounds(455, 348, 92, 14);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Responsables:");
        jPanel8.add(jLabel20);
        jLabel20.setBounds(45, 153, 133, 19);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Contacto:");
        jPanel8.add(jLabel21);
        jLabel21.setBounds(390, 150, 133, 19);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Brandon Londoño Arboleda");
        jPanel8.add(jLabel22);
        jLabel22.setBounds(30, 240, 190, 14);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("305-314-2061");
        jPanel8.add(jLabel24);
        jLabel24.setBounds(390, 240, 110, 14);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("302-226-9718");
        jPanel8.add(jLabel27);
        jLabel27.setBounds(400, 200, 106, 14);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Camilo Guzman Salgado");
        jPanel8.add(jLabel28);
        jLabel28.setBounds(30, 200, 170, 14);

        acercaPanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 929, 370));

        jPanel7.setBackground(new java.awt.Color(86, 31, 223));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ACERCA DEL PROYECTO");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 6, -1, 71));

        acercaPanel.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1328, -1));

        jPanel9.setBackground(new java.awt.Color(86, 31, 223));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        acercaPanel.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 1328, 138));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("SISTEMA DESARROLLADO POR:");
        acercaPanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 580, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        acercaPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 391, -1, -1));

        jTabbedPane.addTab("tab3", acercaPanel);

        getContentPane().add(jTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 47, 1200, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Eliminar();
        consultar();
        nuevo();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Agregar();
        consultar();
        nuevo();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        Modificar();
        consultar();
        nuevo();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        int fila = Tabla.getSelectedRow();
        if (fila == -1) {

            JOptionPane.showMessageDialog(null, "Faltan ingresar datos");
        } else {
            idc = Integer.parseInt((String) Tabla.getValueAt(fila,0) .toString());
            String nom = (String) Tabla.getValueAt(fila,1);
            String ape = (String) Tabla.getValueAt(fila,2);
            int edad = Integer.parseInt((String) Tabla.getValueAt(fila,3) .toString());

            txtId.setText(""+idc);
            txtNombre.setText(nom);
            txtApe.setText(ape);
            txtEdad.setText(""+edad);
        }
    }//GEN-LAST:event_TablaMouseClicked

    private void PanelRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelRegistrarMouseClicked
        jTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_PanelRegistrarMouseClicked

    private void PanelRegistrarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelRegistrarMouseMoved
        PanelRegistrar.setBackground(new Color(86, 31, 223));
    }//GEN-LAST:event_PanelRegistrarMouseMoved

    private void PanelRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelRegistrarMouseExited
        PanelRegistrar.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_PanelRegistrarMouseExited

    private void PanelEstadisticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEstadisticasMouseClicked
        jTabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_PanelEstadisticasMouseClicked

    private void PanelEstadisticasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEstadisticasMouseMoved
        PanelEstadisticas.setBackground(new Color(86, 31, 223));
    }//GEN-LAST:event_PanelEstadisticasMouseMoved

    private void PanelEstadisticasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelEstadisticasMouseExited
        PanelEstadisticas.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_PanelEstadisticasMouseExited

    private void PanelActividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelActividadesMouseClicked
        jTabbedPane.setSelectedIndex(2);
    }//GEN-LAST:event_PanelActividadesMouseClicked

    private void PanelActividadesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelActividadesMouseMoved
        PanelActividades.setBackground(new Color(86, 31, 223));
    }//GEN-LAST:event_PanelActividadesMouseMoved

    private void PanelActividadesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelActividadesMouseExited
        PanelActividades.setBackground(new Color(102,102,255));        
    }//GEN-LAST:event_PanelActividadesMouseExited

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        nuevo();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void labelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMinMouseClicked
        this.setExtendedState(1);
    }//GEN-LAST:event_labelMinMouseClicked

    void Modificar() {
        String nom = txtNombre.getText();
        String ape = txtApe.getText();
        String edad = txtEdad.getText();
        
        try {
            if(nom.equals("") || ape.equals("") || edad.equals("")) {
                JOptionPane.showMessageDialog(null, "Faltan ingresar datos");
                limpiarTabla();
            } else {
                String sql = "Update estudiantes set id='"+idc+"', nombre='"+nom+"',apellido='"+ape+"',edad='"+edad+"' where id=" +idc;
                conet = con1.getConnection();
                st = conet.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Datos de cliente modificado");
                limpiarTabla();

            }
        } catch (Exception e) {
        
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro().setVisible(true);
            }
        });
    }
    
    void consultar() {
        String sql = "select * from estudiantes";
        
        try {
            conet = con1.getConnection();
            st = conet.createStatement();
            rs = st.executeQuery(sql);
            Object[] estudiante = new Object[4];
            modelo = (DefaultTableModel) Tabla.getModel();
                while(rs.next()){
                    estudiante [0] = rs.getInt("id");
                    estudiante [1] = rs.getString("nombre");
                    estudiante [2] = rs.getString("apellido");
                    estudiante [3] = rs.getInt("edad");
                    
                    modelo.addRow(estudiante);
                }
                Tabla.setModel(modelo);
        } catch (Exception e){
        }
    }
    void Agregar() {
        String nom = txtNombre.getText();
        String ape = txtApe.getText();
        String edad = txtEdad.getText();
        
        try {
            if(nom.equals("") || ape.equals("") || edad.equals("")) {
                JOptionPane.showMessageDialog(null, "Faltan ingresar datos");
                limpiarTabla();
            } else {
                String sql = "insert into estudiantes(nombre,apellido,edad) values('"+nom+"','"+ape+"','"+edad+"')";
                conet = con1.getConnection();
                st = conet.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Nuevo estudiante registrado");
                limpiarTabla();

            }
        } catch (Exception e) {
        
        }
    }
    
    void limpiarTabla() {
        for (int i = 0; i <= Tabla.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i-1;
        }
    }
    
void Eliminar() {
    int fila = Tabla.getSelectedRow();
    try {
        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "Estudiante no seleccionado");
            limpiarTabla();
        } else {
            String sql = "delete from estudiantes where id=" + idc;
            conet = con1.getConnection();
            st = conet.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Estudiante eliminado");
            limpiarTabla();
        }
    } catch (Exception e) {
    }
}

void estadisticas() {
    jPanelEstadisticas.setLayout(new FlowLayout());
    jPanelEstadisticas.setBackground(Color.WHITE);
    DefaultCategoryDataset dataset = new DefaultCategoryDataset();
    dataset.setValue(50, "SIN REGISTRAR", "Registro");
    dataset.setValue(85, "REGISTRADOS", "Registro");
    JFreeChart chart = ChartFactory.createBarChart(
        "Registro de estudiantes", 
        "REGISTRO", 
        "Número de estudiantes", 
        dataset);
    ChartPanel chartPanel = new ChartPanel(chart);
    jPanelEstadisticas.add(chartPanel);
}

void nuevo() {
    txtId.setText("");
    txtNombre.setText("");
    txtApe.setText("");
    txtEdad.setText("");
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelActividades;
    private javax.swing.JPanel PanelEstadisticas;
    private javax.swing.JPanel PanelRegistrar;
    private javax.swing.JTable Tabla;
    private javax.swing.JPanel acercaPanel;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JPanel estadisticasPanel;
    private javax.swing.JPanel estudiantesPanel;
    private javax.swing.JLabel foto1;
    private javax.swing.JLabel foto2;
    private javax.swing.JLabel foto3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelEstadisticas;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JLabel labelMin;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField txtApe;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
